### ISSUE TITLE
compilation error for arithmetic.cpp

### ISSUE THREAD

**Issue by lukaszdaniel** [rho-devel/rho#116]
During compilation process, I get the following errors:
arithmetic.cpp:144:16: error: ‘isnan’ was not declared in this scope
arithmetic.cpp:154:16: error: ‘isnan’ was not declared in this scope
arithmetic.cpp:708:15: error: ‘isnan’ was not declared in this scope

If I change isnan() to std::isnan(), everything works fine (i.e. compilation is successful)

Sample output:
arithmetic.cpp: In function ‘int R_IsNA(double)’:
arithmetic.cpp:144:16: error: ‘isnan’ was not declared in this scope
     if (isnan(x)) {
                ^
arithmetic.cpp:144:16: note: suggested alternative:
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /usr/include/boost/iterator/iterator_concepts.hpp:29,
                 from /usr/include/boost/range/concepts.hpp:20,
                 from /usr/include/boost/range/size_type.hpp:20,
                 from /usr/include/boost/range/size.hpp:21,
                 from /usr/include/boost/range/functions.hpp:20,
                 from /usr/include/boost/range.hpp:18,
                 from ../../src/include/rho/ArgList.hpp:32,
                 from ../../src/include/Defn.h:71,
                 from arithmetic.cpp:48:
/usr/include/c++/5/cmath:641:5: note:   ‘std::isnan’
     isnan(_Tp __x)
     ^

**Comment by kmillar** [comment]
It turns out that including math.h and cmath in the same file doesn't really work right.  The issue is that math.h defines some functions (including isnan) as macros, but cmath needs to undefine them so it can implement them as overloaded functions in the std namespace.

It's implementation-defined whether or not cmath puts symbols into the global namespace, which is why this is only broken on some platforms.

Fix coming shortly...

**Comment by kmillar** [comment]
Lukasz, can you check that this works on your machine now?  Thanks.

**Comment by lukaszdaniel** [comment]
It's ok now. Thanks.
