### ISSUE TITLE
Standardising style?

### ISSUE THREAD

**Issue by Ironholds** [rho-devel/rho#7]
One of my biggest annoyances with core as it stands is the lack of comments and the inconsistency in internal style, even within the R. Any objection to me going through and standardising things? It might not do anything for substantive output, but hey, "readability" is absolutely a modern programming paradigm ;).

If that sounds like a good thing to spend time on: thoughts on the appropriate style to use? I've always liked [Hadley's stylistic approach](http://adv-r.had.co.nz/Style.html), although it's not exactly C++-style.

**Comment by kmillar** [comment]
Hi Oliver,

Ideally, those changes would be pushed into the upstream (R-core) implementation of R.  That way, they also get the improvements and we don't make it any harder to keep the CXXR codebase in sync.

Improving the commenting, particularly in the R headers would be a huge improvement IMHO and if R-core decides not to accept changes that improve commenting, then incorporating those changes directly into CXXR seems reasonable.

Making significant style changes is more problematic, because it doesn't have as large a benefit, and it's likely to make it much harder to merge changes between the different versions.  For files that exist in both codebases, I would prefer to have bad style that matches upstream than clean style that doesn't.

For code that's only in CXXR (which is almost entirely C++), the current formatting style is fairly close to WebKit (see the .clang-format file) with doxygen comments.  I wouldn't be adverse to auto-formatting those files into the WebKit (or maybe other)  style with clang-format and/or doing other style cleanup, but IMHO, I don't see a big win there either -- those are the files that are already fairly easy to read.
